# Generated by Django 4.1.7 on 2023-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_pub_profile_perm_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='perm_pub',
        ),
        migrations.AddField(
            model_name='profile',
            name='pub',
            field=models.BooleanField(default=True, verbose_name='Разрешение на публикацию'),
        ),
    ]
