# Generated by Django 4.1.7 on 2023-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kvartiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('city', models.CharField(default='Ростов-на-Дону', max_length=200, verbose_name='Город')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('price', models.SmallIntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('about', models.TextField(max_length=5000, verbose_name='Информация о квартире')),
                ('image', models.ImageField(upload_to='kvartiri/media/main_pics/', verbose_name='Изображение')),
                ('tehnika', models.BooleanField(default=False, verbose_name='Бытовая техника')),
                ('posuda', models.BooleanField(default=False, verbose_name='Столовые принадлежности')),
                ('stiralka', models.BooleanField(default=False, verbose_name='Стиральная машина')),
                ('wifi', models.BooleanField(default=False, verbose_name='Бесплатный WiFi')),
                ('kond', models.BooleanField(default=False, verbose_name='Кондондиционер')),
                ('tv', models.BooleanField(default=True, verbose_name='Телевизор')),
                ('holodilnik', models.BooleanField(default=True, verbose_name='Холодильник')),
                ('micro', models.BooleanField(default=False, verbose_name='Микроволновка')),
                ('tea', models.BooleanField(default=True, verbose_name='Чайник')),
                ('utug', models.BooleanField(default=False, verbose_name='Утюг')),
            ],
            options={
                'verbose_name': 'Квартиру',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
