# Generated by Django 4.1.7 on 2023-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvartiri',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
