# Generated by Django 4.1.7 on 2023-03-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0002_rename_name_kvartiri_title_alter_kvartiri_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvartiri',
            old_name='image',
            new_name='main_image',
        ),
    ]
