# Generated by Django 4.1.7 on 2023-03-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posutochno', '0003_rename_image_kvartiri_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
