# Generated by Django 4.1.7 on 2023-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0004_kvartiri_archived_kvartiri_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartiri',
            name='about',
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архив'),
        ),
    ]
