# Generated by Django 4.1.7 on 2023-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0006_district_kvartiri_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
