# Generated by Django 4.1.7 on 2023-04-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pub'),
        ('posutochno', '0008_alter_kvartiri_options_alter_kvartiri_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='perm_pub',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Разрешение на публикацию'),
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='main_image',
            field=models.ImageField(upload_to='media/kvartiri/main_pics/%Y/%m/', verbose_name='Изображение'),
        ),
    ]
