# Generated by Django 4.1.7 on 2023-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0009_kvartiri_perm_pub_alter_kvartiri_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartiri',
            name='perm_pub',
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='pub',
            field=models.BooleanField(default=True, verbose_name='Разрешение на публикацию'),
        ),
    ]
