# Generated by Django 4.1.7 on 2023-04-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_perm_pub_profile_pub'),
        ('posutochno', '0010_remove_kvartiri_perm_pub_kvartiri_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartiri',
            name='pub',
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='perm_pub',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Разрешение на публикацию'),
        ),
    ]
