# Generated by Django 4.1.7 on 2023-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0011_remove_kvartiri_pub_kvartiri_perm_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='rooms',
            field=models.SmallIntegerField(default=1, max_length=1, verbose_name='Количество комнат'),
        ),
    ]
