# Generated by Django 4.1.7 on 2023-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0013_alter_kvartiri_rooms_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvartiri',
            name='rooms',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='Количество комнат'),
        ),
    ]
