# Generated by Django 4.1.7 on 2023-04-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0014_alter_kvartiri_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 1'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 2'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 3'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 4'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 5'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 6'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 7'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 8'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='media/kvartiri/dop_img/%Y/%m/', verbose_name='Дополнительное фото 9'),
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posutochno.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='main_image',
            field=models.ImageField(upload_to='media/kvartiri/main_pics/%Y/%m/', verbose_name='Главное фото'),
        ),
    ]
