# Generated by Django 4.1.7 on 2023-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0015_alter_images_options_kvartiri_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='pub',
            field=models.BooleanField(default=True, verbose_name='Разрешение на публикацию'),
        ),
    ]
