# Generated by Django 4.1.7 on 2023-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='guest',
            field=models.IntegerField(default=1, verbose_name='Количество спальных мест'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='place',
            field=models.IntegerField(default=1, verbose_name='Количество спальных мест'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='stage',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='time_in',
            field=models.IntegerField(default=12, verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='kvartiri',
            name='time_out',
            field=models.IntegerField(default=14, verbose_name='Время выезда'),
        ),
    ]
