# Generated by Django 4.1.7 on 2023-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posutochno', '0018_kvartiri_guest_kvartiri_place_kvartiri_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartiri',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='VIP статус'),
        ),
        migrations.AlterField(
            model_name='kvartiri',
            name='guest',
            field=models.IntegerField(default=1, verbose_name='Количество гостей'),
        ),
    ]
